Add mailbox command for DDR Generic capture.
elake/ndctl pull request #2
Opened 2022-08-29 20:48 UTC by nishitpatel28

2022-08-30 19:21 UTC, nishitpatel28 reviewed
**ddr_generic_capture output:**
[*********]# ./cxl/cxl perfcnt-ddr-generic-capture mem0
in size: 0x8
command completed successfully
=========================== PERFCNT DDR Generic Capture ============================
Generic Counter Readings:
0
0
0
0
0
0
0
0

**ddr_dfi_capture output:**
[*********]# ./cxl/cxl perfcnt-ddr-dfi-capture mem0
in size: 0x8
command completed successfully
=========================== PERFCNT DDR DFI Capture ============================
DFI Counter Readings:
DFI Counter 17: 0
DFI Counter 20: 0
DFI Counter 21: 0
DFI CH1 Counter 17: 0
DFI CH1 Counter 20: 0
DFI CH1 Counter 21: 0

2022-08-31 17:45 UTC, elake requested changes

2022-08-31 17:45 UTC, elake commented on cxl/lib/libcxl.c
> +	perfcnt_ddr_generic_capture_in->poll_period_ms = poll_period_ms;
```suggestion
	perfcnt_ddr_generic_capture_in->poll_period_ms = cpu_to_le32(poll_period_ms);
```

2022-08-31 17:45 UTC, elake commented on cxl/lib/libcxl.c
> +	u32 poll_period_ms;
```suggestion
	__le32 poll_period_ms;
```

2022-08-31 17:45 UTC, elake commented on cxl/lib/libcxl.c
> +	u32 poll_period_ms;
```suggestion
	__le32 poll_period_ms;
```

2022-08-31 17:45 UTC, elake commented on cxl/lib/libcxl.c
> +	perfcnt_ddr_dfi_capture_in->poll_period_ms = poll_period_ms;
```suggestion
	perfcnt_ddr_dfi_capture_in->poll_period_ms = cpu_to_le32(poll_period_ms);
```

2022-08-31 18:01 UTC, elake approved these changes

2022-08-31 18:01 UTC, merged